name: Cypress tests
on: [push]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout

      - name: Cypress run
        uses: cypress-io/github-action
        with:
          spec: cypress/integration/Mytest/amazon_search.js
