name: Cypress tests
on: [push]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
      runs:
      using: 'node16'
      main: 'main.js'

        uses: cypress-io/github-action@v4
        with:
          config: cypress/integration/Mytest/amazon_search.js
